include other.conf
globinclude kitty.d/**/*.conf
envinclude KITTY_CONF_*
geninclude dynamic.py

# Fonts
font_family		FiraCode Nerd Font
bold_font		false
italic_font     	false
bold_italic_font 	false

font_size 11.0
font_ltr no

# Terminal Cursor
cursor_text_color #111111
cursor_shape_unfocused block
cursor_beam_thickness 6.0
cursor_trail 2
cursor_trail_decay 0.1 0.4

# Color Scheme - Darkside
background #212324
foreground #b9b9b9
cursor #bbbbbb
selection_background #2f3333
color0 #000000
color8 #000000
color1 #f14c36
color9 #b83529
color2 #68c156
color10 #76b768
color3 #f1d32b
color11 #eed64a
color4 #1c98e8
color12 #387bd2
color5 #8e69c8
color13 #957bbd
color6 #1c98e8
color14 #3d96e2
color7 #b9b9b9
color15 #b9b9b9
selection_foreground #212324

# Background
background_opacity 0.75
transparent_background_colors black@2.0
