# --- General ---
general {
    hide_cursor = false
}

# --- Wallpaper/Background --
background {
    monitor =
    path = ~/Imagens/Wallpapers/Lockscreen.jpeg
    blur_passes = 0
}

# --- Profile Image ---
image {
    monitor =
    path = ~/Imagens/Wallpapers/HollowKnight_Profile.jpeg
    border_size = 3
    border_color = rgb(0, 0, 0)
    size = 200
    rounding = -1
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 0, 60
    halign = center
    valign = center
}

# --- Imput Field ---
input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.0)
    outer_color = rgb(182, 199, 228)
    font_color = rgb(182, 199, 228)
    fade_on_empty = false
    rounding = 20
    font_family = Hack Medium
    placeholder_text = Enter Password
    position = 0, -120
    halign = center
    valign = center
}

# --- Time ---
label {
    monitor =
    text = $TIME
    color = rgb(182, 199, 228)
    font_size = 100
    font_family = Hack Medium
    position = 90, -55
    halign = left
    valign = top
}   

# --- Day/Month ---
label {
    monitor =
    text = cmd[update:1000] echo -e "$(date +"%d de %B, %A")"
    color = rgb(182, 199, 228)
    font_size = 22
    font_family = SF Pro Display Bold
    position = 135, -200
    halign = left
    valign = top
}

# CURRENT SONG
label {
    monitor =
    text = cmd[update:1000] echo "$(~/.config/hypr/nowplaying/nowplaying.sh)" 
    color = rgba(255, 255, 255, 0.6)
    font_size = 18
    font_family = JetBrains Mono Nerd, SF Pro Display Bold
    position = 10, 20
    halign = left
    valign = bottom
}

image {
    monitor =
    path = ~/.config/hypr/nowplaying/album_art.jpg
    onclick = "$(~/.config/hypr/nowplaying/nowplaying.sh --toggle)"
    border_size = 2
    border_color = rgba(255, 255, 255, 0)
    size = 100
    rounding = 14
    rotate = 0
    reload_time = -1
    reload_cmd = 
    position = 10, 100
    halign = left
    valign = bottom
}